<script>
  import { Save, RotateCcw, Eye } from 'lucide-svelte'
  import { t } from '../lib/i18n.js'
  import Config from './Config.svelte'
  export let state
  export let runtime
  let tab='routing', draft=structuredClone(state.networkOverrides || {}), raw=JSON.stringify(draft,null,2), message='', error='', saving=false, preview=null
  let base={}; try { base=JSON.parse(state.config) } catch {}
  const tabs=[['routing','Routing','分流'],['dns','DNS','DNS'],['proxy','Proxy','代理'],['adapter','Adapter','网卡'],['advanced','Advanced','高级']]
  const fields={routing:[['client/routing/ip/bypass','Bypass IP/CIDR','直连 IP/CIDR','lines'],['client/routing/dns/rules','DNS rules','DNS 规则','lines'],['client/routing/ip/routes','Routes','普通路由','json'],['client/routing/ip/peer-routes','Peer routes','Peer 前缀路由','json']],dns:[['dns/servers/domestic','Domestic upstream','国内上游','text','doh.pub'],['dns/servers/foreign','Foreign upstream','国外上游','text','cloudflare'],['udp/dns/cache','Cache','缓存','bool',true],['udp/dns/ttl','Cache TTL (seconds)','缓存 TTL（秒）','number',60],['dns/tls/verify-peer','Verify TLS certificates','验证 TLS 证书','bool',true],['dns/ecs/enabled','EDNS client subnet','EDNS 客户端子网','bool',false],['dns/ecs/override-ip','ECS override IP','ECS 出口 IP','text',''],['dns/fake-ip/enabled','Fake-IP','Fake-IP','bool',false],['dns/fake-ip/range','Fake-IP range','Fake-IP 地址池','text','198.18.0.1/16']],proxy:[['client/http-proxy/bind','HTTP bind','HTTP 监听','text','127.0.0.1'],['client/http-proxy/port','HTTP port','HTTP 端口','number',8080],['client/socks-proxy/bind','SOCKS bind','SOCKS 监听','text','127.0.0.1'],['client/socks-proxy/port','SOCKS port','SOCKS 端口','number',1080]]}
  function get(path,fallback='') { const parts=path.split('/'); return parts.reduce((v,k) => v?.[k],draft) ?? parts.reduce((v,k) => v?.[k],base) ?? fallback }
  function set(path,value) { const next=structuredClone(draft), parts=path.split('/'); let target=next; for(const key of parts.slice(0,-1)) { if(!target[key] || typeof target[key] !== 'object') target[key]={}; target=target[key] } target[parts.at(-1)]=value
    for(const name of ['http-proxy','socks-proxy']) if(next.client?.[name]) { next.client[name].bind ??= get(`client/${name}/bind`,'127.0.0.1'); next.client[name].port ??= get(`client/${name}/port`,name === 'http-proxy' ? 8080 : 1080) }
    draft=next; raw=JSON.stringify(draft,null,2); message=''; error='' }
  function edit(path,type,value) { try { set(path,type === 'lines' ? value.split('\n').map((v) => v.trim()).filter(Boolean) : type === 'json' ? JSON.parse(value) : type === 'number' ? Number(value) : value) } catch(cause) { error=String(cause) } }
  function display(path,type,fallback) { const value=get(path,fallback ?? []); return type === 'json' ? JSON.stringify(value,null,2) : type === 'lines' ? Array.isArray(value) ? value.join('\n') : String(value) : value }
  function switchTab(id) { try { draft=JSON.parse(raw); tab=id; error='' } catch(cause) { error=String(cause) } }
  async function save() { saving=true; error=''; try { const value=JSON.parse(raw); await runtime.updateNetwork(value); draft=value; message=$t('Saved; applies on next connection','已保存，下次连接生效') } catch(cause) { error=String(cause) } finally { saving=false } }
  function reset() { draft=structuredClone(state.networkOverrides || {}); raw=JSON.stringify(draft,null,2); message=''; error='' }
  async function inspect() { try { preview=await runtime.preview(); error='' } catch(cause) { error=String(cause) } }
  $: dirty=raw !== JSON.stringify(state.networkOverrides || {},null,2)
</script>
<div class="page"><div class="page-heading"><h1>{$t('Network','网络')}</h1><div class="toolbar"><span class="subtle">{dirty ? $t('Unsaved changes','未保存') : message}</span><button class="icon-button" title={$t('Reset','恢复')} aria-label={$t('Reset','恢复')} on:click={reset}><RotateCcw size={16}/></button><button class="primary-button action" disabled={saving || !dirty || !!error} on:click={save}><Save size={16}/>{$t('Save','保存')}</button></div></div>
  <div class="tabs" role="tablist" aria-label={$t('Network settings','网络设置')}>{#each tabs as [id,en,zh]}<button role="tab" aria-selected={tab === id} class:active={tab === id} on:click={() => switchTab(id)}>{$t(en,zh)}</button>{/each}</div>{#if error}<div class="error-line" role="alert">{error}</div>{/if}
  <section class="band">
    {#if fields[tab]}<div class="network-grid">{#each fields[tab] as [path,en,zh,type,fallback]}<label class="field" class:wide={type === 'lines' || type === 'json'}><span>{$t(en,zh)}</span>{#if type === 'lines' || type === 'json'}<textarea class="text-area short" value={display(path,type,fallback)} on:change={(event) => edit(path,type,event.currentTarget.value)} spellcheck="false"></textarea>{:else if type === 'bool'}<input type="checkbox" role="switch" checked={get(path,fallback)} on:change={(event) => set(path,event.currentTarget.checked)}/>{:else if type === 'number'}<input class="text-input" type="number" min="0" value={get(path,fallback)} on:input={(event) => edit(path,type,event.currentTarget.value)}/>{:else}<input class="text-input" value={get(path,fallback)} on:input={(event) => set(path,event.currentTarget.value)}/>{/if}</label>{/each}</div>
    {:else if tab === 'adapter'}{#if state.settings.connectionMode === 'proxy'}<div class="empty">{$t('Virtual adapter is inactive in proxy mode','本地代理模式不使用虚拟网卡')}</div>{:else}<Config {state} {runtime} section="adapter"/>{/if}
    {:else}<Config {state} {runtime} section="advanced"/><details class="advanced"><summary>GeoIP / GeoSite</summary><textarea class="text-area short" aria-label="Geo rules JSON" value={JSON.stringify(get('geo-rules',{}),null,2)} on:change={(event) => edit('geo-rules','json',event.currentTarget.value)}></textarea></details><details class="advanced"><summary>{$t('Network overrides JSON','网络覆盖 JSON')}</summary><textarea class="text-area spaced" bind:value={raw} on:input={() => error=''} spellcheck="false"></textarea></details><button class="secondary-button action spaced" on:click={inspect}><Eye size={16}/>{$t('Preview saved configuration','预览已保存配置')}</button>{#if preview}<pre class="preview">{JSON.stringify(preview,null,2)}</pre>{/if}{/if}
  </section>
</div>
<style>.network-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:24px; } .wide { grid-column:1/-1; } .short { min-height:130px; } .spaced { margin:18px 0; } .advanced { margin-top:24px; } summary { cursor:pointer; padding:12px 0; color:var(--text-2); } .preview { overflow:auto; max-height:400px; padding:16px; background:var(--surface-raised); font-size:12px; } @media(max-width:760px) { .network-grid { grid-template-columns:1fr; } }</style>
