<script>
  import { FolderOpen, RefreshCw, ShieldCheck, Undo2, Download } from 'lucide-svelte'
  import { t } from '../lib/i18n.js'
  import { downloadText, redactText } from '../lib/security.js'
  export let state
  export let runtime
  let error='', busy=false
  async function run(action) { busy=true; error=''; try { await action() } catch(cause) { error=String(cause) } finally { busy=false } }
  async function diagnostics() { const preview=await runtime.preview(); downloadText('openppp2-diagnostics.json',redactText(JSON.stringify({kernel:state.kernel,connection:state.connection,preview,events:state.events},null,2))) }
</script>
<div class="page"><div class="page-heading"><h1>{$t('Settings','设置')}</h1></div>{#if error}<div class="error-line" role="alert">{error}</div>{/if}
  <section class="band"><h2>{$t('Kernel','内核')}</h2><div class="setting-row"><label class="field grow"><span>ppp.exe</span><input class="text-input mono" value={state.settings.pppPath} on:change={(event) => run(() => runtime.updateSetting('pppPath',event.currentTarget.value.trim()))}/></label><button class="icon-button" disabled={busy} title={$t('Browse','浏览')} aria-label={$t('Browse','浏览')} on:click={() => run(() => runtime.pickExecutable())}><FolderOpen size={17}/></button><button class="icon-button" disabled={busy} title={$t('Inspect kernel','检查内核')} aria-label={$t('Inspect kernel','检查内核')} on:click={() => run(() => runtime.inspectKernel())}><RefreshCw size={17}/></button></div>
    {#if state.kernel}<div class="kernel-details"><span>{state.kernel.version}</span><span>{$t('Statistics','统计')}: {state.kernel.statsSupported ? '✓' : '—'}</span><span>Proxy: {state.kernel.proxySupported ? '✓' : '—'}</span></div>{/if}
    <div class="setting-row"><span>{$t('Privileges','运行权限')}: {state.administrator ? $t('Administrator','管理员') : $t('Standard user','普通用户')}</span><button class="secondary-button action" disabled={busy || !!state.connection.pid || state.administrator} on:click={() => { if(confirm($t('Restart as administrator?','以管理员身份重启？'))) run(() => runtime.elevate()) }}><ShieldCheck size={16}/>{$t('Restart as administrator','管理员重启')}</button></div>
  </section>
  <section class="band"><h2>{$t('System','系统')}</h2>
    {#each [['autostart','Start at sign-in','开机启动'],['closeToTray','Close to tray','关闭到托盘'],['autoSystemProxy','Set system proxy on connection','连接后设置系统代理']] as [key,en,zh]}<label class="setting-row"><span>{$t(en,zh)}</span><input type="checkbox" role="switch" checked={state.settings[key]} disabled={busy || (key === 'autoSystemProxy' && !!state.connection.pid)} on:change={(event) => run(() => runtime.updateSetting(key,event.currentTarget.checked))}/></label>{/each}
    <div class="setting-row"><span>{$t('System proxy recovery','系统代理恢复')}{#if state.proxyRecoveryPending} · {$t('Pending','待处理')}{/if}</span><button class="secondary-button action" disabled={busy} on:click={() => { if(confirm($t('Restore the saved system proxy settings?','恢复保存的系统代理设置？'))) run(() => runtime.restoreProxy(true)) }}><Undo2 size={16}/>{$t('Restore','恢复')}</button></div>
  </section>
  <section class="band"><h2>{$t('Appearance','外观')}</h2><label class="setting-row"><span>{$t('Theme','主题')}</span><select class="select-input" aria-label={$t('Theme','主题')} value={state.settings.appearance} on:change={(event) => run(() => runtime.updateSetting('appearance',event.currentTarget.value))}><option value="system">{$t('System','跟随系统')}</option><option value="light">{$t('Light','浅色')}</option><option value="dark">{$t('Dark','深色')}</option></select></label><label class="setting-row"><span>{$t('Language','语言')}</span><select class="select-input" aria-label={$t('Language','语言')} value={state.settings.language} on:change={(event) => run(() => runtime.updateSetting('language',event.currentTarget.value))}><option>简体中文</option><option>English</option></select></label></section>
  <section class="band"><h2>{$t('Diagnostics','诊断')}</h2><div class="toolbar"><button class="secondary-button action" on:click={() => run(() => runtime.openData())}><FolderOpen size={16}/>{$t('Open data directory','打开数据目录')}</button><button class="secondary-button action" on:click={() => run(diagnostics)}><Download size={16}/>{$t('Export diagnostics','导出诊断')}</button></div></section>
</div>
<style>.setting-row { display:flex; align-items:center; justify-content:space-between; gap:12px; min-height:60px; border-bottom:1px solid var(--border); } .setting-row:last-child { border:0; } .setting-row .select-input { width:160px; } .grow { flex:1; min-width:0; } .kernel-details { display:flex; flex-wrap:wrap; gap:20px; padding:16px 0; color:var(--text-3); } .setting-row:has(.grow) { padding:12px 0; align-items:end; } @media(max-width:760px) { .setting-row { flex-wrap:wrap; padding:12px 0; } }</style>
