<script>
  import { Plus, RefreshCw, Trash2, Pencil, Save, X } from 'lucide-svelte'
  import { t } from '../lib/i18n.js'
  import { formatDateTime } from '../lib/format.js'
  export let state
  export let runtime
  let editing=null, error='', busy=false
  function add() { editing={id:'',name:'',url:'',enabled:true,lastSyncedAt:0,cached:false,error:''} }
  async function run(action) { if(busy) return; busy=true; error=''; try { await action() } catch(cause) { error=String(cause) } finally { busy=false } }
  async function save() { await runtime.saveSubscription(editing); editing=null }
  async function refreshAll() { for(const source of (state.subscription.sources || []).filter((s) => s.enabled)) await runtime.refreshSubscription(source.url,source.id) }
  function remove(source) { if(confirm($t('Delete this subscription?','删除这个订阅？'))) run(() => runtime.deleteSubscription(source.id)) }
</script>
<div class="page"><div class="page-heading"><h1>{$t('Subscriptions','订阅')}</h1><div class="toolbar"><button class="icon-button" disabled={busy} on:click={() => run(refreshAll)} title={$t('Refresh all','全部更新')} aria-label={$t('Refresh all','全部更新')}><RefreshCw size={17}/></button><button class="primary-button action" on:click={add}><Plus size={16}/>{$t('Add source','添加来源')}</button></div></div>
  {#if error}<p role="alert" class="error-line">{error}</p>{/if}
  {#if editing}<form class="editor" on:submit|preventDefault={() => run(save)}><label class="field"><span>{$t('Name','名称')}</span><input class="text-input" bind:value={editing.name} required/></label><label class="field"><span>URL</span><input class="text-input" type="url" bind:value={editing.url} required placeholder="https://"/></label><div class="toolbar"><button class="primary-button action" type="submit" disabled={busy}><Save size={15}/>{$t('Save','保存')}</button><button class="icon-button" type="button" on:click={() => editing=null} title={$t('Cancel','取消')} aria-label={$t('Cancel','取消')}><X size={16}/></button></div></form>{/if}
  {#each state.subscription.sources || [] as source (source.id)}<section class="source-row"><div class="source-details"><h2>{source.name}</h2><div class="subtle">{source.enabled ? $t('Enabled','启用') : $t('Disabled','停用')} · {formatDateTime(source.lastSyncedAt) || $t('Not synced','未同步')}{#if source.cached} · {$t('Cached','缓存')}{/if}</div>{#if source.error}<p class="error-line">{source.error}</p>{/if}</div><div class="toolbar"><input type="checkbox" checked={source.enabled} aria-label={$t('Enable subscription','启用订阅')} disabled={busy} on:change={(event) => run(() => runtime.saveSubscription({...source,enabled:event.currentTarget.checked}))}/><button class="icon-button" disabled={busy} title={$t('Refresh','更新')} aria-label={$t('Refresh','更新')} on:click={() => run(() => runtime.refreshSubscription(source.url,source.id))}><RefreshCw size={15}/></button><button class="icon-button" title={$t('Edit','编辑')} aria-label={$t('Edit','编辑')} on:click={() => editing={...source}}><Pencil size={15}/></button><button class="icon-button" disabled={busy} title={$t('Delete','删除')} aria-label={$t('Delete','删除')} on:click={() => remove(source)}><Trash2 size={15}/></button></div></section>{:else}<div class="empty">{$t('No subscription sources','暂无订阅来源')}</div>{/each}
</div>
<style>.editor { display:grid; grid-template-columns:minmax(120px,.5fr) minmax(0,1fr) auto; gap:12px; align-items:end; padding:20px 0; border-bottom:1px solid var(--border); } .source-row { display:flex; align-items:center; justify-content:space-between; gap:16px; padding:24px 0; border-bottom:1px solid var(--border); } .source-details { min-width:0; overflow-wrap:anywhere; } h2 { font-size:15px; margin:0 0 8px; } @media(max-width:760px) { .editor { grid-template-columns:1fr; } .source-row { align-items:flex-start; flex-wrap:wrap; } }</style>
